package ru.zintur.mobilebase.schema.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import ru.zintur.mobilebase.schema.Customer;
import ru.zintur.mobilebase.schema.Contact;
import ru.zintur.mobilebase.schema.Config;
import ru.zintur.mobilebase.schema.User;

import ru.zintur.mobilebase.schema.dao.CustomerDao;
import ru.zintur.mobilebase.schema.dao.ContactDao;
import ru.zintur.mobilebase.schema.dao.ConfigDao;
import ru.zintur.mobilebase.schema.dao.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig customerDaoConfig;
    private final DaoConfig contactDaoConfig;
    private final DaoConfig configDaoConfig;
    private final DaoConfig userDaoConfig;

    private final CustomerDao customerDao;
    private final ContactDao contactDao;
    private final ConfigDao configDao;
    private final UserDao userDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        configDaoConfig = daoConfigMap.get(ConfigDao.class).clone();
        configDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        customerDao = new CustomerDao(customerDaoConfig, this);
        contactDao = new ContactDao(contactDaoConfig, this);
        configDao = new ConfigDao(configDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(Customer.class, customerDao);
        registerDao(Contact.class, contactDao);
        registerDao(Config.class, configDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        customerDaoConfig.getIdentityScope().clear();
        contactDaoConfig.getIdentityScope().clear();
        configDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public ConfigDao getConfigDao() {
        return configDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
