package ru.zintur.mobilebase.schema.domains;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONTACT".
 */
public class Contact {

    private Long id;
    private String Name;
    private String Status;
    private String Phone;
    private String Mobile;
    private String Email;
    private String Fax;
    private String PhoneEx;
    private long customer;

    public Contact() {
    }

    public Contact(Long id) {
        this.id = id;
    }

    public Contact(Long id, String Name, String Status, String Phone, String Mobile, String Email, String Fax, String PhoneEx, long customer) {
        this.id = id;
        this.Name = Name;
        this.Status = Status;
        this.Phone = Phone;
        this.Mobile = Mobile;
        this.Email = Email;
        this.Fax = Fax;
        this.PhoneEx = PhoneEx;
        this.customer = customer;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

    public String getPhone() {
        return Phone;
    }

    public void setPhone(String Phone) {
        this.Phone = Phone;
    }

    public String getMobile() {
        return Mobile;
    }

    public void setMobile(String Mobile) {
        this.Mobile = Mobile;
    }

    public String getEmail() {
        return Email;
    }

    public void setEmail(String Email) {
        this.Email = Email;
    }

    public String getFax() {
        return Fax;
    }

    public void setFax(String Fax) {
        this.Fax = Fax;
    }

    public String getPhoneEx() {
        return PhoneEx;
    }

    public void setPhoneEx(String PhoneEx) {
        this.PhoneEx = PhoneEx;
    }

    public long getCustomer() {
        return customer;
    }

    public void setCustomer(long customer) {
        this.customer = customer;
    }

}
